config:
  allowDelete: "true"
secrets:
  username: ""
  password: ""
  regSecret: ""
deployment:
  image: priyankaguha/availability:2
  labels:
    env: 'dev'
services:
  type: NodePort
  port: 4005
  nodePort: 30002