apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.secrets.regSecret | quote }}
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson

    