apiVersion: v1
kind: Secret
metadata:
    name: availability-credentials
    namespace: availability
type: Opaque
data:
    BASIC_AUTH_USER: {{ .Values.secrets.username | quote }}
    PASSWORD: {{ .Values.secrets.password | quote }}

