apiVersion: v1
kind: Secret
metadata:
    name: availability-credentials
    namespace: availability
type: Opaque
data:
    BASIC_AUTH_USER: {{ .Values.secrets.username | b64enc }}
    PASSWORD: {{ .Values.secrets.password | b64enc }}

